version: '2'

services:
  ## SERVIDOR WEB ##
  nginx:
    image: bitnami/nginx:latest
    ports:
      - 80:8080
    volumes:
      # ERROR ==> Custom server blocks files were found inside '/bitnami/nginx/conf/vhosts'. This configuration is not supported anymore. Please mount your custom server blocks config files at '/opt/bitnami/nginx/conf/server_blocks' instead.
      #- ./nginx-vhost/myapp.conf:/bitnami/nginx/conf/vhosts/myapp.conf
      - ./nginx-vhost/myapp.conf:/opt/bitnami/nginx/conf/server_blocks/myapp.conf
      - ./app:/app

  ## SERVIDOR BBDD ##
  mariadb:
    image: bitnami/mariadb:latest
    environment:
      - MARIADB_ROOT_PASSWORD=awcatadau2020
    volumes:
      #abans llançar  sudo chown -R 1001:1001 mysqldata/
      - ./mysqldata:/bitnami/mariadb

  ## LLENGUATGE DE SERVIDOR ##
  php-fpm:
    #image: bitnami/php-fpm:latest
    image: bitnami/php-fpm:5.6
    volumes:
      - ./app:/app